export const BOOKS_ACTIONS = {
  BOOKS_LIST_LOADING: 'BOOKS_LIST_LOADING',
  BOOKS_LIST_FAIL: 'BOOKS_LIST_FAIL',
  BOOKS_LIST_SUCCESS: 'BOOKS_LIST_SUCCESS',
}
export const ADD_BOOK_ACTIONS = {
  ADD_BOOK_LOADING: 'ADD_BOOK_LOADING',
  ADD_BOOK_FAIL: 'ADD_BOOK_FAIL',
  ADD_BOOK_SUCCESS: 'ADD_BOOK_SUCCESS',
}
export const DELETE_BOOK_ACTIONS = {
  DELETE_BOOK_LOADING: 'DELETE_BOOK_LOADING',
  DELETE_BOOK_FAIL: 'DELETE_BOOK_FAIL',
  DELETE_BOOK_SUCCESS: 'DELETE_BOOK_SUCCESS',
}
export const EDIT_BOOK_ACTIONS = {
  EDIT_BOOK_LOADING: 'EDIT_BOOK_LOADING',
  EDIT_BOOK_FAIL: 'EDIT_BOOK_FAIL',
  EDIT_BOOK_SUCCESS: 'EDIT_BOOK_SUCCESS',
}